FROM node:14.12.0

WORKDIR /app
# copy js and json file
COPY ./*.js* /app/
COPY ./yarn.lock /app/

# Install dev modules
RUN yarn install

# Copy and compile files
COPY src ./src
CMD [ "yarn", "dev" ]