FROM node:16.13

WORKDIR /app
# copy package.json and yarn.lock
COPY ./package.json /app/
COPY ./yarn.lock /app/

# Install dev modules
RUN yarn install

# copy js and json files
COPY ./*.js* /app/
# Copy source files
COPY src ./src
CMD [ "yarn", "dev" ]