version: "3.7"

services:
  api: # api
    image: findme-api-development
    container_name: findme-api
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    depends_on:
      - redis
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - SECRETKEY=sssshhhhhi
      - PORT=3000
      - REDIS_URL=redis://findme-api-redis

  redis: # Redis server
    image: redis:6.2.0-alpine
    container_name: findme-api-redis
    ports:
      - "6379:6379"
