name: Publish Docker image
on:
  push:
    branches:
      - dev
jobs:
  buildx:
    name: build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        if: success()
        env:
          IMAGE: ${{ secrets.DOCKER_IMAGE_TAG_NAME }}
          PLATFORM: linux/arm/v7,linux/amd64
        run: |
          docker buildx build --push --platform $PLATFORM -t $IMAGE:latest .
      - name: Deploy to cluster
        if: ${{ success() }}
        uses: steebchen/kubectl@v2.0.0
        env:
          DEPLOYMENT: ${{ secrets.K8S_DEPLOYMENT_NAME }}
          CONTAINER: ${{ secrets.K8S_CONTAINER_NAME }}
          IMAGE: ${{ secrets.DOCKER_IMAGE_TAG_NAME }}:latest
        with:
          config: ${{ secrets.K8S_CONFIG_DATA }}
          version: v1.22.1
          command: set image deployment/$DEPLOYMENT $CONTAINER=$IMAGE

      - name: Verify deployment
        if: ${{ success() }}
        uses: steebchen/kubectl@v2.0.0
        env:
          DEPLOYMENT: ${{ secrets.K8S_DEPLOYMENT_NAME }}
        with:
          config: ${{ secrets.K8S_CONFIG_DATA }}
          version: v1.22.1
          command: rollout status deployment/$DEPLOYMENT
